routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::auth();
Route::get('/logout', 'Auth\LoginController@logout');
Route::group(['middleware' => ['auth']], function () {
    /**
     * Main
     */
    Route::get('/', 'PagesController@dashboard');
    Route::get('/user/{user}','UserProfileController@show')->name('user.show');
    Route::get('login/{provider}', 'Auth\SocialAuthController@redirectToProvider')->name('social.login');
    Route::get('login/{provider}/callback', 'Auth\SocialAuthController@handleProviderCallback')->name('social.login.callback');
    Route::get('/qrgen','PagesController@qrgen');
    Route::get('dashboard', 'PagesController@dashboard')->name('dashboard');
    Route::POST('dashboard', 'PagesController@dashboard')->name('dashboard');

    Route::get('sendcoin', 'PagesController@sendabbccoin')->name('sendcoin');
    Route::POST('sendcoin', 'PagesController@sendabbccoin')->name('sendcoin');

    Route::get('addresses', 'PagesController@listaddresses')->name('addresses');
    Route::POST('addresses', 'PagesController@listaddresses')->name('addresses');
    Route::get('trans_history', 'PagesController@trans_history')->name('trans_history');
    Route::get('marketcapapi', 'PagesController@marketcapapiprices')->name('marketcapapi');

    Route::get('backupwallet', 'PagesController@backupWallet')->name('backupwallet');
    Route::POST('backupwallet', 'PagesController@backupWallet')->name('backupwallet');

    Route::get('impwallet', 'PagesController@importwallet')->name('impwallet');
    Route::POST('impwallet', 'PagesController@importwallet')->name('impwallet');

    /**
     * Users
     */
    Route::group(['prefix' => 'users'], function () {
        Route::get('/destroy/{id}','UsersController@destroy')->name('users.destroy');
    });
    Route::resource('users', 'UsersController');
    Route::get('users/{id}', 'UsersController@edit');
    Route::get('userprofile/{id}', 'UsersController@userprofile');

});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/complete-registration', 'Auth\RegisterController@completeRegistration');

Route::post('/2fa', function () {
    return redirect(URL()->previous());
})->name('2fa')->middleware('2fa');

Route::get('/2fa', function () {
    return redirect('/');
})->name('2fa')->middleware('2fa');

Route::get('/re-authenticate', 'PagesController@reauthenticate');

Route::get('/verifyemail/{token}', 'Auth\RegisterController@verify');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex, nofollow">
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../assets/img/favicon.png">
    <title>ABBC</title>
    <!-- Fonts -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet'
          type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700" rel='stylesheet' type='text/css'>

    <!-- Styles -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    {{-- <link href="{{ elixir('css/app.css') }}" rel="stylesheet"> --}}

    <style>
        body {
            font-family: 'Lato';
        }

        .fa-btn {
            margin-right: 6px;
        }
    </style>
</head>
<body id="app-layout">

<div style="text-align: center; margin-bottom:20px;"><img src="{{ asset('images/abbc_logo.png') }}" width="100px"
                                                          alt=""></div>


@yield('content')

<!-- JavaScripts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
{{-- <script src="{{ elixir('js/app.js') }}"></script> --}}
</body>
</html>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ABBC ERP</title>
    <link href="{{ URL::asset('css/jasny-bootstrap.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ URL::asset('css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ URL::asset('css/jquery.dataTables.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ URL::asset('css/dropzone.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ URL::asset('css/jquery.atwho.min.css') }}" rel="stylesheet" type="text/css">

    <link rel="stylesheet" href="{{ asset(elixir('css/app.css')) }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <meta name="csrf-token" content="{{ csrf_token() }}"/>
	<style>
	.dot {
  height: 20px;
  width: 20px;
  background-color: #bbb;
  border-radius: 50%;
  display: inline-block;
  text-align:center;
}
	</style>
</head>
<body>

<div id="wrapper">

    <button type="button" class="navbar-toggle menu-txt-toggle" style=""><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span></button>

    <div class="navbar navbar-default navbar-top">
        <!--NOTIFICATIONS START-->
<div class="menu">
   
    <div class="notifications-header"><p>Notifications</p> </div>
  <!-- Menu -->
 <ul>
 <?php $notifications = auth()->user()->unreadNotifications; ?>

    @foreach($notifications as $notification)
   
    <a href="{{ route('notification.read', ['id' => $notification->id])  }}" onClick="postRead({{ $notification->id }})">
    <li> 
 <img src="/{{ auth()->user()->avatar }}" class="notification-profile-image">
    <p>{{ $notification->data['message']}}</p></li>
    </a>
    @endforeach 
  </ul>
</div>

       <div class="dropdown" id="nav-toggle">
            <a id="notification-clock" role="button" data-toggle="dropdown">
               
				
				@if($notifications->count()>0) <i class="glyphicon glyphicon-bell">
				<span class = "dot" style="background-color:red;color:white;">{{ $notifications->count() }}</span></i>
				@else
					 <i class="glyphicon glyphicon-bell">
					<span  style="color:white;">{{ $notifications->count() }}</span>
				</i>
				
				@endif
            </a>
                </div>
                    @push('scripts')
                    <script>
$('#notification-clock').click(function(e) {
  e.stopPropagation();
  $(".menu").toggleClass('bar')
});
$('body').click(function(e) {
  if ($('.menu').hasClass('bar')) {
    $(".menu").toggleClass('bar')
  }
})      
                  id = {};
                        function postRead(id) {
                            $.ajax({
                                type: 'post',
                                url: '{{url('/notifications/markread')}}',
                                data: {
                                    id: id,
                                },
                                headers: {
                                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                                }
                            });

                        }

                    </script>
                @endpush
        <!--NOTIFICATIONS END-->
        <button type="button" id="mobile-toggle" class="navbar-toggle mobile-toggle" data-toggle="offcanvas" data-target="#myNavmenu">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>


    <!-- /#sidebar-wrapper -->
    <!-- Sidebar menu -->

    <nav id="myNavmenu" class="navmenu navmenu-default navmenu-fixed-left offcanvas-sm" role="navigation">
        <div class="list-group panel">
            <p class=" list-group-item siderbar-top" title=""><img src="{{url('images/abbc_logo.png')}}" alt="" width= "100"></p>
            <a href="{{route('dashboard', \Auth::id())}}" class=" list-group-item" data-parent="#MainMenu"><i
                        class="glyphicon sidebar-icon glyphicon-dashboard"></i><span id="menu-txt">{{ __('Dashboard') }}</span> </a>

            <a href="#marketing" class="list-group-item " data-toggle="collapse" data-parent="#MainMenu" ><i
                        class="glyphicon sidebar-icon glyphicon-dashboard" ></i><span id="menu-txt">{{ __('Marketing') }}</span>
                <i class="ion-chevron-up  arrow-up sidebar-arrow"></i></a>

            @if(isset($departments) && is_object($departments))
            @foreach($departments as $dept)
                @if($dept->name=='Marketing')
                    <div class="collapse" id="marketing">
                        <a href="{{route('marketing')}}" class="list-group-item childlist">{{ __('Dashboard') }}</a>
                        {{--<a href="{{ route('topic.index')}}" class="list-group-item childlist">{{ __('Email Supoort Issues') }}</a>--}}
                    </div>
                    @endif
            @endforeach
            @endif

            <a href="{{ route('topic.index')}}" class="list-group-item"><i
                        class="glyphicon sidebar-icon glyphicon-dashboard" ></i>
                <span id="menu-txt">{{ __('Email Supoort Issues') }}</span></a>


             @if(Entrust::hasRole('administrator'))
                <a href="#settings" class=" list-group-item" data-toggle="collapse" data-parent="#MainMenu"><i
                            class="glyphicon sidebar-icon glyphicon-cog"></i><span id="menu-txt">{{ __('Settings') }}</span>
                <i class="ion-chevron-up  arrow-up sidebar-arrow"></i></a>
                <div class="collapse" id="settings">
                    <a href="{{ route('settings.index')}}"
                       class="list-group-item childlist">{{ __('Overall Settings') }}</a>

                    <a href="{{ route('roles.index')}}"
                       class="list-group-item childlist">{{ __('Role Management') }}</a>
                </div>
            @endif
            <a href="{{ url('/logout') }}" class=" list-group-item impmenu" data-parent="#MainMenu"><i
                        class="glyphicon sidebar-icon glyphicon-log-out"></i><span id="menu-txt">{{ __('Sign Out') }}</span> </a>

        </div>
    </nav>


    <!-- Page Content -->
    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <h1>@yield('heading')</h1>
                    @yield('content')
                </div>
            </div>
        </div>
        @if($errors->any())
            <div class="alert alert-danger">
                @foreach($errors->all() as $error)
                    <p>{{ $error }}</p>
                @endforeach
            </div>

        @endif
        @if(Session::has('flash_message_warning'))
             <message message="{{ Session::get('flash_message_warning') }}" type="warning"></message>
        @endif
        @if(Session::has('flash_message'))
            <message message="{{ Session::get('flash_message') }}" type="success"></message>
        @endif
    </div>
    <!-- /#page-content-wrapper -->
</div>
    <script type="text/javascript" src="{{ URL::asset('js/app.js') }}"></script>
    <script type="text/javascript" src="{{ URL::asset('js/dropzone.js') }}"></script>
    <script type="text/javascript" src="{{ URL::asset('js/jquery.dataTables.min.js') }}"></script>
    <script type="text/javascript" src="{{ URL::asset('js/jasny-bootstrap.min.js') }}"></script>
    <script type="text/javascript" src="{{ URL::asset('js/jquery.caret.min.js') }}"></script>
        <script type="text/javascript" src="{{ URL::asset('js/jquery.atwho.min.js') }}"></script>
@stack('scripts')
</body>

</html>

resources/views/layouts/mastersidebar.blade.php
<div class="sidebar">
    <!--
      Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red"
  -->
  <div class="sidebar-wrapper">
    <div class="logo">
        <a href="javascript:void(0)" class="simple-text logo-mini">
            <img src="{{ asset('images/abbc_logo.png') }}" width="100px"
      alt="">
        </a>
        <a href="/dashboard" class="simple-text logo-normal">
            ABBC HYBRID WALLET
        </a>
    </div>


      <ul class="nav">
          <li>
              <a href="{{route('dashboard')}}">
                  <i class="tim-icons icon-chart-pie-36"></i>
                  <p style="font-size: 13px; font-weight: 500;">Dashboard</p>
              </a>
          </li>

          <li>
              <a href="{{route('sendcoin')}}">
                  <i class="tim-icons icon-send"></i>
                  <p style="font-size: 13px; font-weight: 500;">Send</p>
              </a>
          </li>

          {{--<li>
              <a href="{{route('backupwallet')}}">
                  <i class="tim-icons icon-wallet-43"></i>
                  <p style="font-size: 13px; font-weight: 500;">Backup</p>
              </a>
          </li>


          <li>
              <a href="{{route('impwallet')}}">
                  <i class="tim-icons icon-cloud-upload-94"></i>
                  <p style="font-size: 13px; font-weight: 500;">Import</p>
              </a>
          </li>--}}

          <li>
              <a href="{{route('trans_history')}}">
                  <i class="tim-icons icon-bullet-list-67"></i>
                  <p style="font-size: 13px; font-weight: 500;">Transaction History</p>
              </a>
          </li>

          <li>
              <a href="{{route('marketcapapi')}}">
                  <i class="tim-icons icon-money-coins"></i>
                  <p style="font-size: 13px; font-weight: 500;">CoinMarket Cap</p>
              </a>
          </li>


      </ul>

        </div>
    </div>

resources/views/layouts/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            <div class="navbar-toggle d-inline">
                <button type="button" class="navbar-toggler">
                    <span class="navbar-toggler-bar bar1"></span>
                    <span class="navbar-toggler-bar bar2"></span>
                    <span class="navbar-toggler-bar bar3"></span>
                </button>
            </div>
            {{--<a class="navbar-brand" href="javascript:void(0)">Dashboard</a>--}}
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-bar navbar-kebab"></span>
        <span class="navbar-toggler-bar navbar-kebab"></span>
        <span class="navbar-toggler-bar navbar-kebab"></span>
    </button>
    <div class="collapse navbar-collapse" id="navigation">
        <ul class="navbar-nav ml-auto">

            <li class="dropdown nav-item">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                    <div class="photo">
                        <img src="/{{ auth()->user()->avatar }}" alt="Profile Photo">
                    </div>
                    <b class="caret d-none d-lg-block d-xl-block"></b>
                    <p class="d-lg-none">
                        Log out
                    </p>
                </a>
                <ul class="dropdown-menu dropdown-navbar">
                    <?php if(auth()->user()->id==8){ ?>
                    <li class="nav-link">
                        <a href="{{route('users.index')}}"
                           class="nav-item dropdown-item">All Users</a>
                    </li>
                    <?php } ?>
                    <li class="nav-link">
                    <a href="/userprofile/{{auth()->user()->id}}" class="nav-item dropdown-item">Profile</a>
                   </li>

                    <li class="dropdown-divider"></li>
                    <li class="nav-link">
                        <a href="{{route('logout')}}" class="nav-item dropdown-item">Log out</a>
                    </li>
                </ul>
            </li>
            <li class="separator d-lg-none"></li>
        </ul>
    </div>
</div>


</nav>